user_input = input('Enter your text : ')
data = list(user_input)
output = ''
for i in data:
    if i == 'a':
        output += '.- '
    if i == 'b':
        output += '-... '
    if i == 'c':
        output += '-.-. '
    if i == 'd':
        output += ' '
    if i == 'e':
        output += '. '
    if i == 'f':
        output += '..-. '
    if i == 'g':
        output += '--. '
    if i == 'h':
        output += '.... '
    if i == 'i':
        output += '.. '
    if i == 'g':
        output += '.--- '
    if i == 'k':
        output += '-.- '
    if i == 'l':
        output += '.-.. '
    if i == 'm':
        output += '-- '
    if i == 'n':
        output += '-. '
    if i == 'o':
        output += '--- '
    if i == 'p':
        output += '.--. '
    if i == 'q':
        output += '--.- '
    if i == 'r':
        output += '.-. '
    if i == 's':
        output += '... '
    if i == 't':
        output += '- '
    if i == 'u':
        output += '..- '
    if i == 'v':
        output += '...- '
    if i == 'w':
        output += '.-- '
    if i == 'x':
        output += '-..- '
    if i == 'y':
        output += '-.-- '
    if i == 'z':
        output += '--.. '
    if i == '1':
        output += '.---- '
    if i == '2':
        output += '..--- '
    if i == '3':
        output += '...-- '
    if i == '4':
        output += '....- '
    if i == '5':
        output += '..... '
    if i == '6':
        output += '-.... '
    if i == '7':
        output += '--... '
    if i == '8':
        output += '---.. '
    if i == '9':
        output += '----. '
    if i == '0':
        output += '----- '

print(output)